version: '2'

volumes:
  VOLUME-test:
    external: false


services:
  gk:
    image: nginx
    expose:
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"
    # volumes_from:
    #   - VOLUME-gk
    links:
       # - www:www.internal
       # - oauth2proxy:oauth2proxy.internal
       - jupyter-notebook:jupyter-notebook.internal

  test1:
    image: busybox
    command: tail -f /dev/null
    volumes:
      - VOLUME-test:/test

  test2:
    image: busybox
    command: tail -f /dev/null
    volumes:
      - VOLUME-test:/test


  s3:
    image: lphoward/fake-s3
    expose:
      - "4569"
    ports:
      - "4569:4569"
    volumes_from:
      - VOLUME-s3

  VOLUME-s3:
    image: busybox:latest
    volumes:
      - /var/lib/sximada/s3/fakes3_root:/fakes3_root

  sns:
    image: sximada-sns
    build:
      context: docker-fake-sns
      dockerfile: Dockerfile
    expose:
      - "9292"
    ports:
      - "9292:9292"

  # airflow:
  #   image: airflow
  #   build:
  #     context: docker-airflow
  #     dockerfile: Dockerfile

  # VOLUME-gk:
  #   image: busybox
  #   volumes:
  #     - /var/lib/sximada/gk/etc/nginx/conf.d:/etc/nginx/conf.d
  #     - /var/lib/sximada/gk/etc/ssl/private:/etc/ssl/private

  # oauth2proxy:
  #   image: a5huynh/oauth2_proxy
  #   command: "--upstream=http://www.internal --http-address=0.0.0.0:4180 --email-domain=gmail.com -redirect-url='https//sximada.com/oauth2/callback/'"
  #   expose:
  #     - "4180"
  #   env_file:
  #     - databag/oauth2proxy.env
  #   links:
  #      - www:www.internal

  # www:
  #   image: nginx
  #   volumes_from:
  #     - VOLUME-www

  # VOLUME-www:
  #   image: busybox
  #   volumes:
  #     - /var/src/sximada/www:/var/www/sximada/www
  #     - /var/lib/sximada/www/etc/nginx/conf.d:/etc/nginx/conf.d
  #     - /var/lib/sximada/www/etc/ssl/private:/etc/ssl/private


  # fluentd:
  #   image: fluent/fluentd:latest
  #   env_file:
  #     - databag/fluentd.env
  #   ports:
  #     - 24224:24224
  #   volumes_from:
  #     - volume-fluentd
  # volume-fluentd:
  #   image: busybox:latest
  #   volumes:
  #     - /var/lib/sximada/fluentd/fluentd/etc:/fluentd/etc
  #     - /var/lib/sximada/fluentd/fluentd/plugins:/fluentd/plugins

  # sximada:
  #   image: nginx
  #   logging:
  #     driver: fluentd
  #     options:
  #       fluentd-address: localhost:24224
  #       fluentd-tag: docker.{{.FullID}}
  #   depends_on:
  #     - fluentd
  #   expose:
  #     - "80"
  #     - "443"
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes_from:
  #     - volume-sximada
  #   links:
  #     - www:www.internal
  #     - djangoexample:djangoexample.internal
  # volume-sximada:
  #   image: busybox
  #   volumes:
  #     - /var/lib/sximada/sximada/etc/nginx/conf.d:/etc/nginx/conf.d
  #     - /var/lib/sximada/sximada/etc/ssl/private/sximada:/etc/ssl/private/sximada

  # www:
  #   image: nginx
  #   logging:
  #     driver: fluentd
  #     options:
  #       fluentd-address: localhost:24224
  #       fluentd-tag: docker.{{.FullID}}
  #   depends_on:
  #     - fluentd
  #   expose:
  #     - "80"
  #   volumes_from:
  #     - volume-www
  # volume-www:
  #   image: busybox
  #   volumes:
  #     - /var/lib/sximada/www/etc/nginx/conf.d:/etc/nginx/conf.d
  #     - /var/lib/sximada/www/etc/ssl/private/sximada:/etc/ssl/private/sximada
  #     - /var/src/sximada/www:/var/www/www.sximada.com

  # djangoexample:
  #   build: djangoexample
  #   env_file:
  #     - databag/djangoexample.env
  #   volumes_from:
  #     - volume-djangoexample
  #   links:
  #     - redis:redis.internal
  #     - mysql:mysql.internal
  #   expose:
  #     - 8000
  # volume-djangoexample:
  #   image: busybox
  #   volumes:
  #     - /var/src/sximada/djangoexample:/srv/sximada/djangoexample/src
  #     - /var/lib/sximada/djangoexample/var:/srv/sximada/djangoexample/var
  #     - /var/lib/sximada/djangoexample/log:/srv/sximada/djangoexample/log
  #     - /var/lib/sximada/djangoexample/etc:/srv/sximada/djangoexample/etc
  #     - /var/lib/sximada/djangoexample/settings:/srv/sximada/djangoexample/settings
  #     - /var/lib/sximada/djangoexample/tmp:/srv/sximada/djangoexample/tmp

  # # nginx:
  # #   image: nginx:latest
  # #   logging:
  # #     driver: fluentd
  # #     options:
  # #       fluentd-address: localhost:24224
  # #       fluentd-tag: docker.{{.FullID}}
  # #   depends_on:
  # #     - fluentd
  # #   expose:
  # #     - 80
  # #     - 443
  # #   ports:
  # #     - 80:80
  # #     - 443:443

  # # apt-cacher-ng:
  # #   build: apt-cacher-ng
  # #   logging:
  # #     driver: fluentd
  # #     options:
  # #       fluentd-address: localhost:24224
  # #       fluentd-tag: docker.{{.FullID}}
  # #   depends_on:
  # #     - fluentd
  # #   ports:
  # #     - 3142:3142
  # #   volumes_from:
  # #     - volume-apt-cacher-ng

  # # volume-apt-cacher-ng:
  # #   image: busybox:latest
  # #   volumes:
  # #     - /var/lib/sximada/apt-cacher-ng/var/cache/apt-cacher-ng:/var/cache/apt-cacher-ng

  # rundeck:
  #   image: gzm55/rundeck

  # # elasticsearch:
  # #   image: elasticsearch:latest

  # # mongodb:
  # #   image: mongo:latest

  # # postgresql:
  # #   image: postgres:latest

  # # logstash:
  # #   image: logstash:latest

  # # rabbitmq:
  # #   image: rabbitmq:latest

  # redis:
  #   image: redis:latest

  # mysql:
  #   image: mysql:latest
  #   env_file:
  #     - databag/mysql.env
  #   volumes_from:
  #     - volume-mysql

  # volume-mysql:
  #   image: busybox
  #   volumes:
  #     - /var/lib/sximada/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  #     - /var/lib/sximada/mysql/var/lib/mysql:/var/lib/mysql
  #     - /var/lib/sximada/mysql/var/log/mysql:/var/log/mysql



  # sns:
  #   image: feathj/fake-sns
  #   volumes_from:
  #     - VOLUME-sns
  # VOLUME-s3:
  #   image: busybox:latest
  #   volumes:
  #     - /var/lib/sximada/s3/fakes3_root:/fakes3_root

  # # openstack-swift:
  # #   image: serverascode/swift-onlyone

  # # node:
  # #   image: node:latest

  # # wordpress:
  # #   image: wordpress:latest

  # # httpd:
  # #   image: httpd:latest

  # # java:
  # #   image: java:latest

  # # python:
  # #   image: python:latest

  # # tomcat:
  # #   image: tomcat:latest

  # # php:
  # #   image: php:latest

  # # golang:
  # #   image: golang:latest

  # # alpine:
  # #   image: alpine:latest

  # # haproxy:
  # #   image: haproxy:latest

  # # mariadb:
  # #   image: mariadb:latest

  # # ruby:
  # #   image: ruby:latest

  # # rails:
  # #   image: rails:latest

  # # memcached:
  # #   image: memcached:latest

  # # cassandra:
  # #   image: cassandra:latest

  # # cassandra:
  # #   image: cassandra:latest

  # # kibana:
  # #   image: kibana:latest

  # # sentry:
  # #   image: sentry:latest

  # # redmine:
  # #   image: redmine:latest

  # # jenkins:
  # #   image: jenkins:latest

  # # rethinkdb:
  # #   image: rethinkdb:latest

  # # haskell:
  # #   image: haskell:latest

  # # clojure:
  # #   image: clojure:latest

  # # julia:
  # #   image: julia:latest

  # # erlang:
  # #   image: erlang:latest

  # # aerospike:
  # #   image: aerospike:latest

  # # owncloud:
  # #   image: owncloud:latest

  # # mono:
  # #   image: mono:latest

  # # odoo:
  # #   image: odoo:latest

  # # tensorflow:
  # #   image: b.gcr.io/tensorflow/tensorflow:latest

  # # google-auth-proxy:
  # #   image: a5huynh/google-auth-proxy

  # # ffmpeg:
  # #   image: cellofellow/ffmpeg

  # # powerdns:
  # #   image: tutum/powerdns
  # #   # image: secns/pdns:latest

  # # tor:
  # #   image: chriswayg/tor-alpine

  # # registry:
  # #   image: registry:2.0

  # # warehouse:
  # #   build: warehouse

  # # npm-proxy-cache:
  # #   image: kudoz/npm-proxy-cache:latest

  # # # gitorious:
  # # #   build: gitorious-docker

  # # docker-python:
  # #   build: docker-python

  # # sinopia:  # Private npm repository server
  # #   image: rnbwd/sinopia

  jupyter-notebook:
    image: jupyter/notebook
    expose:
      - 8888
    volumes_from:
      - VOLUME-jupyter-notebook
  #   # logging:
  #   #   driver: fluentd
  #   #   options:
  #   #     fluentd-address: localhost:24224
  #   #     fluentd-tag: docker.{{.FullID}}
  #   # depends_on:
  #   #   - fluentd

  VOLUME-jupyter-notebook:
    image: busybox
    volumes:
      - /var/lib/sximada/jupyter-notebook:/notebooks

  # # mitmproxy:
  # #   image: mitmproxy/mitmproxy:latest
  # #   expose:
  # #     - 8080
  # #     - 8081

  # # volume-mitmproxy:
  # #   image: busybox:latest
  # #   volumes:
  # #     - /var/lib/sximada/mitmproxy/certs:/certs
