version: '2'

services:
  nginx:
    image: nginx:latest
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        fluentd-tag: docker.{{.FullID}}
    depends_on:
      - fluentd
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443

  fluentd:
    image: fluent/fluentd:latest
    env_file:
      - databag/fluentd.env
    ports:
      - 24224:24224
    volumes_from:
      - volume-fluentd

  apt-cacher-ng:
    image: sameersbn/apt-cacher-ng:latest
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        fluentd-tag: docker.{{.FullID}}
    depends_on:
      - fluentd
    ports:
      - 3142:3142
    volumes_from:
      - volume-apt-cacher-ng

  volume-fluentd:
    image: busybox:latest
    volumes:
      - /var/lib/sximada/fluentd/fluentd/etc:/fluentd/etc
      - /var/lib/sximada/fluentd/fluentd/plugins:/fluentd/plugins

  volume-apt-cacher-ng:
    image: busybox:latest
    volumes:
      - /var/lib/sximada/apt-cacher-ng/var/cache/apt-cacher-ng:/var/cache/apt-cacher-ng
